// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Common.Grpc {
  public static partial class GrpcMessageService
  {
    static readonly string __ServiceName = "Common.Grpc.GrpcMessageService";

    static readonly grpc::Marshaller<global::Common.Grpc.ServiceMessage2> __Marshaller_ServiceMessage2 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Grpc.ServiceMessage2.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Grpc.Noop> __Marshaller_Noop = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Grpc.Noop.Parser.ParseFrom);

    static readonly grpc::Method<global::Common.Grpc.ServiceMessage2, global::Common.Grpc.Noop> __Method_Send = new grpc::Method<global::Common.Grpc.ServiceMessage2, global::Common.Grpc.Noop>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_ServiceMessage2,
        __Marshaller_Noop);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Common.Grpc.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcMessageService</summary>
    public abstract partial class GrpcMessageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Common.Grpc.Noop> Send(global::Common.Grpc.ServiceMessage2 request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcMessageService</summary>
    public partial class GrpcMessageServiceClient : grpc::ClientBase<GrpcMessageServiceClient>
    {
      /// <summary>Creates a new client for GrpcMessageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GrpcMessageServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcMessageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GrpcMessageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GrpcMessageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GrpcMessageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Common.Grpc.Noop Send(global::Common.Grpc.ServiceMessage2 request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Common.Grpc.Noop Send(global::Common.Grpc.ServiceMessage2 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Grpc.Noop> SendAsync(global::Common.Grpc.ServiceMessage2 request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Grpc.Noop> SendAsync(global::Common.Grpc.ServiceMessage2 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GrpcMessageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcMessageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GrpcMessageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send).Build();
    }

  }
}
#endregion
